//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2020Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2020Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1728
        ///1954
        ///1850
        ///1825
        ///1732
        ///1536
        ///1759
        ///1877
        ///1400
        ///1579
        ///1708
        ///1047
        ///1810
        ///558
        ///1132
        ///1608
        ///1857
        ///1756
        ///1834
        ///1743
        ///1888
        ///1660
        ///1642
        ///1726
        ///541
        ///1519
        ///1407
        ///1875
        ///1618
        ///1331
        ///1878
        ///1626
        ///1200
        ///1346
        ///1830
        ///1403
        ///1557
        ///1890
        ///1543
        ///823
        ///1435
        ///1903
        ///1377
        ///1931
        ///1885
        ///1422
        ///1411
        ///1563
        ///1818
        ///1643
        ///2004
        ///1364
        ///1446
        ///1071
        ///1699
        ///1140
        ///1617
        ///1974
        ///1758
        ///1537
        ///1980
        ///1709
        ///1812
        ///1178
        ///1822
        ///1648
        ///1517
        ///1477
        ///1935
        ///1848
        ///1534
        ///1734
        ///1484
        ///1985
        ///1485
        ///1963
        ///1329
        ///1809
        ///1380
        ///1552
        ///1895
        ///215
        ///1844
        ///1138
        ///1194
        ///1938
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Input {
            get {
                return ResourceManager.GetString("Day01Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 388075.
        /// </summary>
        internal static string Day01Part1Output {
            get {
                return ResourceManager.GetString("Day01Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 293450526.
        /// </summary>
        internal static string Day01Part2Output {
            get {
                return ResourceManager.GetString("Day01Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-4 m: mrfmmbjxr
        ///5-16 b: bbbbhbbbbpbxbbbcb
        ///7-8 x: qxrxmxccxxx
        ///9-11 k: kkkkkkktmkhk
        ///8-12 g: sgwvdxzhkvndv
        ///6-9 v: zvmvvmvvvd
        ///8-19 f: ffffsplmfflffhtfrfj
        ///5-16 p: pppppppppspppjpcp
        ///2-3 w: wwmw
        ///7-19 j: jjjjjjjjjjjjjjjjjjvj
        ///5-9 q: wqzqqqqqq
        ///14-15 g: gggggggggglggfgg
        ///4-6 p: tppzkppdt
        ///11-14 p: vppgpktpppppptpppqp
        ///5-9 f: bfflffrfgf
        ///7-9 p: ppppptbzn
        ///1-3 l: lllvn
        ///2-4 g: qvcdg
        ///1-3 m: wsmdv
        ///1-5 v: vvvvvvvv
        ///10-14 l: lckqlgjllltlwbl
        ///3-4 t: bsttftltjhbqbgtm
        ///15-17 j: jjzjjjjjhjjjjjjpzjj
        ///2-3 t: thtt
        ///6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Input {
            get {
                return ResourceManager.GetString("Day02Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 607.
        /// </summary>
        internal static string Day02Part1Output {
            get {
                return ResourceManager.GetString("Day02Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 321.
        /// </summary>
        internal static string Day02Part2Output {
            get {
                return ResourceManager.GetString("Day02Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...#.....#.......##......#.....
        ///...#..................#........
        ///....##....#.......#............
        ///.........#.......#.......#.....
        ///..#..............#.........#..#
        ///.....#.........#....#....#....#
        ///....##..........#.#.##.........
        ///...#....##...#...#...#.#..#....
        ///...#.......###..........#......
        ///.........#.....#....#...#.#....
        ///.#...###..#..##..#.........###.
        ///#.#...#..........###...#....#..
        ///#....#.#..#..........#.......#.
        ///.#..#........##.#..............
        ///............#..#.#............#
        ///.............#... [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Input {
            get {
                return ResourceManager.GetString("Day03Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 220.
        /// </summary>
        internal static string Day03Part1Output {
            get {
                return ResourceManager.GetString("Day03Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2138320800.
        /// </summary>
        internal static string Day03Part2Output {
            get {
                return ResourceManager.GetString("Day03Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..##.......
        ///#...#...#..
        ///.#....#..#.
        ///..#.#...#.#
        ///.#...##..#.
        ///..#.##.....
        ///.#.#.#....#
        ///.#........#
        ///#.##...#...
        ///#...##....#
        ///.#..#...#.#.
        /// </summary>
        internal static string Day03TestInput {
            get {
                return ResourceManager.GetString("Day03TestInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:2029 byr:1931 hcl:z cid:128
        ///ecl:amb hgt:150cm iyr:2015 pid:148714704
        ///
        ///byr:2013 hgt:70cm pid:76982670 ecl:#4f9a1c
        ///hcl:9e724b eyr:1981 iyr:2027
        ///
        ///pid:261384974 iyr:2015
        ///hgt:172cm eyr:2020
        ///byr:2001 hcl:#59c2d9 ecl:amb cid:163
        ///
        ///eyr:2024 hcl:#b6652a
        ///cid:340
        ///byr:1929 ecl:oth iyr:2014 pid:186640193
        ///hgt:193in
        ///
        ///iyr:2015 eyr:2024 hgt:184cm
        ///ecl:blu hcl:#a97842 byr:1959 pid:932817398
        ///
        ///iyr:1933 hcl:7c63aa cid:72 eyr:2028
        ///ecl:hzl
        ///byr:2009 hgt:164cm pid:104496116
        ///
        ///byr:1980
        ///hgt:181cm pid:192793676 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Input {
            get {
                return ResourceManager.GetString("Day04Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 233.
        /// </summary>
        internal static string Day04Part1Output {
            get {
                return ResourceManager.GetString("Day04Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111.
        /// </summary>
        internal static string Day04Part2Output {
            get {
                return ResourceManager.GetString("Day04Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFBBBFBLRL
        ///BFFFBFBRRR
        ///BFFFBFBLRL
        ///BFFBFBBLRR
        ///BBFFBFFRLL
        ///BFFFBFBRLR
        ///FFFFBBBRLR
        ///BBFFFBBRRR
        ///BBFBFBBRRR
        ///BFFBBBFLRR
        ///FFBBFBBRLR
        ///BBFFBFFLLL
        ///BFFFBFBLLR
        ///FBBFFBFLRR
        ///FBBFBBFRRL
        ///BFFBBBBRRR
        ///BFBBBBFLLL
        ///BFFBFBFLRR
        ///FBBFFBFRRR
        ///FFBFBFBLRL
        ///BFFFFBFLRR
        ///FBBFFFFLRR
        ///BFFFBBBLLL
        ///BFBFFFBRLL
        ///FFBBBBBRLL
        ///FFBBFFBLLR
        ///FBFFBBFLRL
        ///FFBFFBBRRL
        ///BFBBBBFLLR
        ///BFFFFBFRRL
        ///BFFBFFFLLL
        ///FBFFFBFLRL
        ///FBBBFFFLLL
        ///FFBFBBFRLR
        ///FBBBFBFRRL
        ///BFBBBFBLLL
        ///FBFFFBFLRR
        ///FBFBFFBLRR
        ///BFFFFBFLRL
        ///FBFBFFFRRL
        ///FBBFBFBLRL
        ///FBBFFBFLLL
        ///FBFBBBBR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05Input {
            get {
                return ResourceManager.GetString("Day05Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 878.
        /// </summary>
        internal static string Day05Part1Output {
            get {
                return ResourceManager.GetString("Day05Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 504.
        /// </summary>
        internal static string Day05Part2Output {
            get {
                return ResourceManager.GetString("Day05Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lznroxbqymvfijpwkec
        ///gljkpwyvsbmroziefnqxc
        ///bmkiewyxjfzqrocnlpv
        ///ibewnmlkzfcrjyvxopq
        ///fkmxpbvjiwlrzocqyne
        ///
        ///khicbaxyvmlgorz
        ///baonifgtlkrmcxhzv
        ///albmyvgrihxkzoc
        ///vmcizkpglyoarxbh
        ///
        ///mxrufizdpe
        ///tmowfuynajqlivhgskrcb
        ///
        ///xwqpuirsmaoyldgbzft
        ///odlyigpqsmbvtzauxr
        ///aymdshiprbguoqzxtl
        ///zdylrimtjpxeosaqubg
        ///tlbzigadxkoqnurcsmyp
        ///
        ///jadtruwhinqog
        ///vitasqdnoeghjwuz
        ///aigqhdowjsetun
        ///unhqwogdjait
        ///
        ///om
        ///oep
        ///
        ///vknfwpuzisty
        ///tzifluwnspv
        ///wispvfntuz
        ///
        ///znupcl
        ///lcnpuz
        ///lkuznecp
        ///pczunlx
        ///nzubclp
        ///
        ///cunfkismz
        ///lbhypaje
        ///
        ///r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06Input {
            get {
                return ResourceManager.GetString("Day06Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6782.
        /// </summary>
        internal static string Day06Part1Output {
            get {
                return ResourceManager.GetString("Day06Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3596.
        /// </summary>
        internal static string Day06Part2Output {
            get {
                return ResourceManager.GetString("Day06Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mirrored gold bags contain 3 light teal bags.
        ///clear gold bags contain 5 light maroon bags, 4 pale tomato bags, 5 clear blue bags.
        ///dark olive bags contain 5 plaid black bags, 2 dim plum bags, 2 light cyan bags.
        ///bright white bags contain 2 pale violet bags, 5 mirrored orange bags, 3 faded beige bags.
        ///posh green bags contain 4 shiny gray bags.
        ///posh lime bags contain 3 muted lavender bags, 1 clear magenta bag, 5 muted orange bags, 3 mirrored cyan bags.
        ///striped turquoise bags contain 3 pale red bags, 4 wav [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07Input {
            get {
                return ResourceManager.GetString("Day07Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Day07Part1Output {
            get {
                return ResourceManager.GetString("Day07Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Day07Part2Output {
            get {
                return ResourceManager.GetString("Day07Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acc -13
        ///jmp +37
        ///acc -19
        ///jmp +1
        ///jmp +1
        ///jmp +413
        ///acc +10
        ///jmp +194
        ///jmp +587
        ///jmp +388
        ///acc +48
        ///nop +284
        ///acc +35
        ///jmp +239
        ///acc +0
        ///jmp +58
        ///acc +22
        ///acc +45
        ///acc +25
        ///acc +23
        ///jmp +544
        ///jmp +610
        ///nop +273
        ///jmp +554
        ///jmp +584
        ///acc +30
        ///jmp +481
        ///acc +29
        ///jmp +342
        ///acc +9
        ///acc +23
        ///nop +377
        ///jmp +483
        ///acc +33
        ///jmp +128
        ///nop +560
        ///nop +437
        ///jmp +485
        ///acc +2
        ///acc +30
        ///jmp +456
        ///acc +0
        ///acc -15
        ///nop +126
        ///acc +47
        ///jmp +299
        ///acc +36
        ///acc +9
        ///jmp -21
        ///acc +10
        ///acc +26
        ///acc -3
        ///acc +31
        ///jmp +337
        ///nop +517
        ///j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08Input {
            get {
                return ResourceManager.GetString("Day08Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Day08Part1Output {
            get {
                return ResourceManager.GetString("Day08Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Day08Part2Output {
            get {
                return ResourceManager.GetString("Day08Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///17
        ///27
        ///3
        ///14
        ///30
        ///50
        ///23
        ///9
        ///43
        ///18
        ///47
        ///11
        ///19
        ///37
        ///41
        ///2
        ///21
        ///40
        ///36
        ///15
        ///8
        ///7
        ///13
        ///49
        ///5
        ///22
        ///48
        ///28
        ///10
        ///12
        ///14
        ///27
        ///16
        ///9
        ///24
        ///17
        ///18
        ///20
        ///11
        ///19
        ///23
        ///25
        ///21
        ///26
        ///29
        ///30
        ///31
        ///15
        ///32
        ///33
        ///34
        ///22
        ///36
        ///37
        ///28
        ///64
        ///35
        ///41
        ///27
        ///38
        ///63
        ///40
        ///56
        ///45
        ///47
        ///52
        ///42
        ///43
        ///57
        ///44
        ///46
        ///48
        ///49
        ///54
        ///50
        ///70
        ///58
        ///62
        ///55
        ///66
        ///82
        ///85
        ///120
        ///94
        ///78
        ///98
        ///83
        ///89
        ///164
        ///87
        ///97
        ///86
        ///110
        ///168
        ///96
        ///116
        ///99
        ///186
        ///264
        ///160
        ///141
        ///144
        ///253
        ///121
        ///149
        ///167
        ///181
        ///161
        ///170
        ///165
        ///169
        ///172
        ///197
        ///251
        ///185
        ///182
        ///333
        ///363
        ///257
        ///195
        ///215
        ///22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day09Input {
            get {
                return ResourceManager.GetString("Day09Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Day09Part1Output {
            get {
                return ResourceManager.GetString("Day09Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Day09Part2Output {
            get {
                return ResourceManager.GetString("Day09Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noup.
        /// </summary>
        internal static string Day10Input {
            get {
                return ResourceManager.GetString("Day10Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Day10Part1Output {
            get {
                return ResourceManager.GetString("Day10Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Day10Part2Output {
            get {
                return ResourceManager.GetString("Day10Part2Output", resourceCulture);
            }
        }
    }
}
