//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2020Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2020Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1728
        ///1954
        ///1850
        ///1825
        ///1732
        ///1536
        ///1759
        ///1877
        ///1400
        ///1579
        ///1708
        ///1047
        ///1810
        ///558
        ///1132
        ///1608
        ///1857
        ///1756
        ///1834
        ///1743
        ///1888
        ///1660
        ///1642
        ///1726
        ///541
        ///1519
        ///1407
        ///1875
        ///1618
        ///1331
        ///1878
        ///1626
        ///1200
        ///1346
        ///1830
        ///1403
        ///1557
        ///1890
        ///1543
        ///823
        ///1435
        ///1903
        ///1377
        ///1931
        ///1885
        ///1422
        ///1411
        ///1563
        ///1818
        ///1643
        ///2004
        ///1364
        ///1446
        ///1071
        ///1699
        ///1140
        ///1617
        ///1974
        ///1758
        ///1537
        ///1980
        ///1709
        ///1812
        ///1178
        ///1822
        ///1648
        ///1517
        ///1477
        ///1935
        ///1848
        ///1534
        ///1734
        ///1484
        ///1985
        ///1485
        ///1963
        ///1329
        ///1809
        ///1380
        ///1552
        ///1895
        ///215
        ///1844
        ///1138
        ///1194
        ///1938
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Input {
            get {
                return ResourceManager.GetString("Day01Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 388075.
        /// </summary>
        internal static string Day01Part1Output {
            get {
                return ResourceManager.GetString("Day01Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 293450526.
        /// </summary>
        internal static string Day01Part2Output {
            get {
                return ResourceManager.GetString("Day01Part2Output", resourceCulture);
            }
        }
    }
}
